# Generated by Django 6.0.4 on 2026-05-03 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderSupportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('complaint', 'Complaint'), ('feedback', 'Feedback'), ('inquiry', 'Inquiry'), ('service_delay', 'Service Delay'), ('safety_concern', 'Safety Concern'), ('app_issue', 'App Issue'), ('other', 'Other')], max_length=40)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rider_reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Support Report',
                'verbose_name_plural': 'Rider Support Reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
